class @Manuscript extends Minimongoid
  @_collection: new Meteor.Collection "manuscripts"

  @traditions: [
    "Amharic"
    "Armenian"
    "Coptic"
    "Ge'ez"
    "Latin"
    "Syriac"
  ]

  @languages: [
    "Amharic"
    "Arabic"
    "Armenian"
    "Church Slavonic"
    "Coptic"
    "Ge'ez"
    "Georgian"
    "Greek"
    "Hebrew"
    "Kurdish"
    "Latin"
    "Old Church Slavonic"
    "Persian"
    "Polish"
    "Russian"
    "Syriac"
    "Turkish"
    "Ukranian"
  ]

  @alphabet: [
    "Arabic"
    "Armenian"
    "Coptic"
    "Cyrillic"
    "Ge'ez"
    "Georgian"
    "Greek"
    "Hebrew (or Armanic)"
    "Roman"
    "Syriac"
  ]

  @scripts: [
    "Abbasid bookhand"
    "Ancient Roman"
    "Asomtavruli"
    "Beneventan"
    "Bolorgir"
    "Bookhand"
    "Carolingian"
    "Christian Palestinian Aramaic"
    "Coptic"
    "Cyrillic bookhand"
    "Cyrillic cursive"
    "Cursive"
    "Dīwānī"
    "Early Jewish"
    "Eash Syriac"
    "Erkat’agir"
    "Erkat’agir-bolorgir"
    "Estrangela"
    "Gǝʿǝz"
    "Glagolitic"
    "Gothic"
    "Half-Uncial"
    "Hasmonean"
    "Herodian"
    "Humanist"
    "Insular"
    "Maghribi"
    "Melkite"
    "Minuscule"
    "Muḥaqqaq"
    "Mxedruli"
    "Naskh"
    "Nastaʿlīq"
    "New Abbasid style"
    "Nōtrgir"
    "Nusxuri"
    "Papyri bookhand"
    "Papyri cursive"
    "Rayḥān"
    "Riqāʿ"
    "Ruqʿa"
    "Semi-cursive"
    "Semiuncial"
    "Serto"
    "Shikasta"
    "Šłagir"
    "Taʿlīq"
    "Tawqīʿ"
    "Thuluth"
    "Uncial"
    "Visigothic"
  ]
