require '/imports/contrib/jquery-ui/jquery-ui.js'
require '/imports/contrib/jquery-ui-touch-punch/jquery-ui.touch-punch.min.js'
require '/imports/contrib/jquery-ui-dialogextend/jquery-ui.dialogextend.coffee'
require '/imports/contrib/jquery-ui-dialogextend/jquery-ui.dialogextend.collapse.coffee'
require '/imports/contrib/jquery-ui-dialogextend/jquery-ui.dialogextend.minimize.coffee'
require '/imports/contrib/jquery-ui-dialogextend/jquery-ui.dialogextend.maximize.coffee'
require '/imports/contrib/jquery-scrollTo/jquery.scrollTo.min.js'
require '/imports/contrib/openseadragon/openseadragon.js'
require '/imports/contrib/jquery-tooltipster/jquery.tooltipster.min.js'
require '/imports/contrib/bootstrap/bootstrap.js'
require '/imports/contrib/bootstrap-slider/bootstrap-slider.js'
require '/imports/contrib/bootstrap-slider/css/bootstrap-slider.min.css'
require '/imports/contrib/color-picker/js/bootstrap-colorpicker.min.js'
require '/imports/contrib/color-picker/css/bootstrap-colorpicker.min.css'
require '/imports/contrib/select2/select2.js'
require '/imports/contrib/select2/select2.css'
require '/imports/contrib/select2/select2-bootstrap.css'

